// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR0bKjtguplmsgxBNT5jHfN2Zv7pkLElQ',
    appId: '1:776698029426:web:734e95640332afe72869eb',
    messagingSenderId: '776698029426',
    projectId: 'udemy-flutter-sns-27082',
    authDomain: 'udemy-flutter-sns-27082.firebaseapp.com',
    storageBucket: 'udemy-flutter-sns-27082.appspot.com',
    measurementId: 'G-093M3RVHVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP2dSZ52924FqAn_AXMid3W0Y4QCBJiFI',
    appId: '1:776698029426:android:9822b0db9f280bf02869eb',
    messagingSenderId: '776698029426',
    projectId: 'udemy-flutter-sns-27082',
    storageBucket: 'udemy-flutter-sns-27082.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3o4Yh0MdNtJtHOjeef4w-_aloNvVz-8',
    appId: '1:776698029426:ios:2e255663f1fd46942869eb',
    messagingSenderId: '776698029426',
    projectId: 'udemy-flutter-sns-27082',
    storageBucket: 'udemy-flutter-sns-27082.appspot.com',
    iosClientId: '776698029426-7bavie64kc4gbp5rl4pd3dj8he8hld5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0805',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3o4Yh0MdNtJtHOjeef4w-_aloNvVz-8',
    appId: '1:776698029426:ios:5815726ed8d7209d2869eb',
    messagingSenderId: '776698029426',
    projectId: 'udemy-flutter-sns-27082',
    storageBucket: 'udemy-flutter-sns-27082.appspot.com',
    iosClientId: '776698029426-nclged0orn61qajtsvelnhfj4hvc5chr.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0805.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR0bKjtguplmsgxBNT5jHfN2Zv7pkLElQ',
    appId: '1:776698029426:web:fbc74f95cad997e62869eb',
    messagingSenderId: '776698029426',
    projectId: 'udemy-flutter-sns-27082',
    authDomain: 'udemy-flutter-sns-27082.firebaseapp.com',
    storageBucket: 'udemy-flutter-sns-27082.appspot.com',
    measurementId: 'G-Z0RC8V5T2T',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAR0bKjtguplmsgxBNT5jHfN2Zv7pkLElQ',
    appId: '1:776698029426:web:157f8821d4415b922869eb',
    messagingSenderId: '776698029426',
    projectId: 'udemy-flutter-sns-27082',
    authDomain: 'udemy-flutter-sns-27082.firebaseapp.com',
    storageBucket: 'udemy-flutter-sns-27082.appspot.com',
    measurementId: 'G-3G4W08K6BD',
  );
}
